<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakit\Petstore\Models\Operations;


class ListPetsResponse
{
	
    public string $contentType;
    
    /**
     * unexpected error
     * 
     * @var ?\speakit\Petstore\Models\Shared\Error $error
     */
	
    public ?\speakit\Petstore\Models\Shared\Error $error = null;
    
    /**
     * $headers
     * 
     * @var ?array<string, array<string>> $headers
     */
	
    public ?array $headers = null;
    
    /**
     * A paged array of pets
     * 
     * @var ?array<\speakit\Petstore\Models\Shared\Pet> $pets
     */
	
    public ?array $pets = null;
    
	
    public int $statusCode;
    
	
    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;
    
	public function __construct()
	{
		$this->contentType = "";
		$this->error = null;
		$this->headers = null;
		$this->pets = null;
		$this->statusCode = 0;
		$this->rawResponse = null;
	}
}
