<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakit\Petstore;

/**
 * PetstoreBuilder is used to configure and build an instance of the SDK.
 * 
 * @package speakit\Petstore
 */
class PetstoreBuilder
{
    private ?\GuzzleHttp\ClientInterface $client;
    
    private string $serverUrl;
    /** @var array<string, string> */
    private ?array $params;

    public function __construct() {
        $this->client = null;
        
        $this->serverUrl = '';
        $this->params = null;
    }

    /**
     * setClient allows setting a custom Guzzle client for the SDK to make requests with.
     *
     * @param \GuzzleHttp\ClientInterface $client
     * @return PetstoreBuilder
     */
    public function setClient(\GuzzleHttp\ClientInterface $client): PetstoreBuilder
    {
        $this->client = $client;
        return $this;
    }
    
    /**
     * setServerUrl is used to configure the server URL for the SDK, and optionally template any parameters in the URL.
     *
     * @param string $serverUrl
     * @param array<string, string> $params
     * @return PetstoreBuilder
     */
    public function setServerUrl(string $serverUrl, ?array $params = null): PetstoreBuilder
    {
        $this->serverUrl = $serverUrl;
        if ($params !== null) {
            $this->params = $params;
        }
        return $this;
    }
    
    /**
     * build is used to build the SDK with any of the configured options.
     *
     * @return Petstore
     */
    public function build(): Petstore
    {
        return new Petstore($this->client, $this->serverUrl, $this->params);
    }
}